"""
Email Service — gửi email qua SendGrid.

Hỗ trợ:
  - Email notify lead mới cho team AMD
  - Email follow-up tự động cho khách hàng
  - Template Jinja2 với placeholder {{name}}, {{contact}}, v.v.
"""
from __future__ import annotations

import asyncio
import logging
from typing import Any

from jinja2 import Template

from app.core.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()


def _get_sendgrid():
    """Lazy import SendGrid — tránh crash khi chưa install."""
    try:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail
        return SendGridAPIClient, Mail
    except ImportError:
        logger.warning("sendgrid package chưa được install — email bị tắt")
        return None, None


def render_template(template_str: str, context: dict[str, Any]) -> str:
    """Render Jinja2 template với context."""
    return Template(template_str).render(**context)


def send_email(
    to_email: str,
    subject: str,
    body_html: str,
    body_text: str | None = None,
) -> bool:
    """
    Gửi email qua SendGrid.
    Trả về True nếu thành công, False nếu lỗi.
    """
    if not settings.sendgrid_api_key:
        logger.warning("SendGrid API key chưa được cấu hình — bỏ qua gửi email")
        return False

    SendGridAPIClient, Mail = _get_sendgrid()
    if SendGridAPIClient is None:
        return False

    message = Mail(
        from_email=(settings.email_from, settings.email_from_name),
        to_emails=to_email,
        subject=subject,
        html_content=body_html,
        plain_text_content=body_text or body_html,
    )

    try:
        sg = SendGridAPIClient(settings.sendgrid_api_key)
        response = sg.send(message)
        logger.info(f"Email sent to {to_email} — status {response.status_code}")
        return response.status_code in (200, 201, 202)
    except Exception as e:
        logger.error(f"Failed to send email to {to_email}: {e}")
        return False


# ─────────────────────────────────────────────
# Template mặc định
# ─────────────────────────────────────────────
DEFAULT_LEAD_NOTIFY_SUBJECT = "[AMD Lead] {{name}} — {{project_type}} — {{created_at}}"

DEFAULT_LEAD_NOTIFY_HTML = """
<h2>Có lead mới từ website chatbot</h2>
<table>
  <tr><td><b>Tên:</b></td><td>{{name}}</td></tr>
  <tr><td><b>Liên hệ:</b></td><td>{{contact}}</td></tr>
  {% for key, val in extra_fields.items() %}
  <tr><td><b>{{key}}:</b></td><td>{{val}}</td></tr>
  {% endfor %}
</table>
<h3>Tóm tắt hội thoại</h3>
<pre>{{chat_summary}}</pre>
<p><a href="{{dashboard_url}}">Xem lead trong dashboard →</a></p>
<hr>
<small>Auto-generated by AMD Website Chatbot</small>
"""

DEFAULT_FOLLOWUP_SUBJECT = "AMD AI Solutions — Theo dõi dự án {{project_type}}"

DEFAULT_FOLLOWUP_HTML = """
<p>Chào {{name}},</p>
<p>Trước đó anh/chị có liên hệ với AMD về dự án <b>{{project_type}}</b>.</p>
<p>AMD muốn hỏi thăm anh/chị đã cân nhắc thêm chưa ạ?</p>
<p>Nếu cần trao đổi thêm, anh/chị có thể reply email này hoặc nhắn Zalo <b>{{zalo_number}}</b>.</p>
<br>
<p>Trân trọng,<br>Team AMD AI Solutions</p>
"""


async def async_send_lead_notify(
    lead_id: int,
    name: str,
    contact: str,
    extra_fields: dict[str, Any],
    chat_log: list[dict],
    dashboard_base_url: str = "http://localhost:5173",
    custom_subject_template: str | None = None,
    custom_body_template: str | None = None,
) -> bool:
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(
        None,
        send_lead_notify,
        lead_id,
        name,
        contact,
        extra_fields,
        chat_log,
        dashboard_base_url,
        custom_subject_template,
        custom_body_template,
    )


async def async_send_followup_email(
    to_email: str,
    lead_data: dict[str, Any],
    template_str: str | None = None,
    subject_str: str | None = None,
    zalo_number: str = "",
) -> bool:
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(
        None,
        send_followup_email,
        to_email,
        lead_data,
        template_str,
        subject_str,
        zalo_number,
    )


def send_lead_notify(
    lead_id: int,
    name: str,
    contact: str,
    extra_fields: dict[str, Any],
    chat_log: list[dict],
    dashboard_base_url: str = "http://localhost:5173",
    custom_subject_template: str | None = None,
    custom_body_template: str | None = None,
) -> bool:
    """Gửi email thông báo lead mới cho team AMD."""
    from datetime import datetime

    chat_summary = "\n".join(
        f"{m['role'].upper()}: {m['content']}" for m in chat_log[-20:]
    )

    context = {
        "name": name or "Không rõ",
        "contact": contact or "Không rõ",
        "extra_fields": extra_fields,
        "chat_summary": chat_summary,
        "dashboard_url": f"{dashboard_base_url}/leads/{lead_id}",
        "project_type": extra_fields.get("project_type", "Chưa xác định"),
        "created_at": datetime.now().strftime("%d/%m/%Y %H:%M"),
    }

    subject = render_template(custom_subject_template or DEFAULT_LEAD_NOTIFY_SUBJECT, context)
    body = render_template(custom_body_template or DEFAULT_LEAD_NOTIFY_HTML, context)

    return send_email(
        to_email=settings.email_notify_to,
        subject=subject,
        body_html=body,
    )


def send_followup_email(
    to_email: str,
    lead_data: dict[str, Any],
    template_str: str | None = None,
    subject_str: str | None = None,
    zalo_number: str = "",
) -> bool:
    """Gửi email follow-up tự động cho khách hàng."""
    context = {**lead_data, "zalo_number": zalo_number}
    subject = render_template(subject_str or DEFAULT_FOLLOWUP_SUBJECT, context)
    body = render_template(template_str or DEFAULT_FOLLOWUP_HTML, context)
    return send_email(to_email=to_email, subject=subject, body_html=body)
